#!/nix/store/ffli6m23501dkiznwlkf6n4xvrj02snr-bash-4.4-p23/bin/bash
set -eu -o pipefail
IFS=$'\n'

function url() {
    local QID=${1:-0}
    local MR=${2:-1000} 
    local S=${3:-music}
    local SI=$((QID*MR))
    echo "https://www.youtube.com/audioswap_ajax?action_get_tracks=1&dl=true&sh=true&s=${S}&mr=${MR}&si=${SI}&qid=${QID}"
}

QID=$((0))
MR=$((1000)) # max mr=1000
# S="music"
S="soundeffects"

curl --cookie "cookies.txt" "$(url $QID $MR $S)" --output "${S}-${MR}-${QID}.json"
while [ "$(jq '.has_more' "${S}-${MR}-${QID}.json")" = "true" ]; do
    QID=$((QID+1))
    curl --cookie "cookies.txt" "$(url $QID $MR $S)" --output "${S}-${MR}-${QID}.json"
done
jq --slurp --compact-output '{ tracks: map(.tracks[]) }' "${S}-${MR}-"*.json > "${S}-${MR}.json"

# output some statistics here
set -x
jq '.tracks | length' "${S}-${MR}.json"
set +x

# proper metadata stuff
# for song in $(jq --compact-output '.tracks | .[]' "${S}-${MR}.json"); do
#     echo "$song" | jq '.'
# done

# just download
jq -r '.tracks[].download_url' "${S}-${MR}.json" > "${S}-${MR}.txt"
mkdir --parents "${S}-${MR}"
cd "${S}-${MR}"
# aria2c --auto-file-renaming=false -x 8 -j 16 -i ../"${S}-${MR}.txt"

