#!/nix/store/ffli6m23501dkiznwlkf6n4xvrj02snr-bash-4.4-p23/bin/bash

function url() {
    local QID=${1:-0}
    local MR=${2:-1000} 
    local S=${3:-music}
    local SI=$((QID*MR))
    echo "https://www.youtube.com/audioswap_ajax?action_get_tracks=1&dl=true&sh=true&s=${S}&mr=${MR}&si=${SI}&qid=${QID}"
}

QID=$((0))
MR=$((1000)) # max mr=1000
S="music"

aria2c --out="${S}-${MR}-${QID}.json" --load-cookies=cookies.txt "$(url $QID $MR $S)"
cp "${S}-${MR}-${QID}.json" "${S}-${MR}.json"

while [ $(jq '.has_more' "${S}-${MR}.json") = "true"]; do
    echo $(jq '.has_more' "${S}-${MR}.json")
done